plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: true

Bundler/DuplicatedGroup:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Bundler/GemFilename:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/InsecureProtocolSource:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Gemspec/DependencyVersion:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/DuplicatedAssignment:
  Enabled: true

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent
  IndentationWidth: ~

Layout/AssignmentIndentation:
  Enabled: true
  IndentationWidth: ~

Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
  Severity: warning

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: either

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/ClassStructure:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
  Severity: warning

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Layout/EmptyComment:
  Enabled: true
  AllowBorderComment: true
  AllowMarginComment: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMultilineCondition:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: false
  NumberOfEmptyLines: 1

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EndAlignment:
  Enabled: true
  Severity: warning

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: native

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
  AllowBeforeTrailingComments: true
  ForceEqualSignAlignment: false

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/HeredocArgumentClosingParenthesis:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationStyle:
  Enabled: true
  IndentationWidth: ~

# TODO: enable when fixed - https://github.com/rubocop/rubocop/issues/14747
Layout/IndentationWidth:
  Enabled: false
  Width: 2
  AllowedPatterns: []

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineHashKeyLineBreaks:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodCallIndentation:
  Enabled: true
  IndentationWidth: ~

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodParameterLineBreaks:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented
  IndentationWidth: ~

Layout/ParameterAlignment:
  Enabled: true
  IndentationWidth: ~

Layout/RedundantLineBreak:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: true
  EnforcedStyleInsidePipes: no_space

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

Layout/SpaceBeforeBrackets:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: true
  AllowForAlignment: true

Layout/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: require_no_space

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true

Layout/SpaceInsideParens:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideReferenceBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Layout/SpaceInsideStringInterpolation:
  Enabled: true
  EnforcedStyle: no_space

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Layout/TrailingWhitespace:
  Enabled: true
  AllowInHeredoc: true

Layout/EmptyLinesAfterModuleInclusion:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRange:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true
  # Intentionally disable autocorrect to force us to intentionally decide
  # whether assignment is intended as opposed to comparison
  AutoCorrect: false

Lint/ConstantResolution:
  Enabled: false

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateMatchPattern:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/EmptyInPattern:
  Enabled: false

Lint/EmptyWhen:
  Enabled: true
  AllowComments: true

Lint/HashCompareByIdentity:
  Enabled: false

Lint/HeredocMethodCallPosition:
  Enabled: false

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: false

Lint/InheritException:
  Enabled: true
  EnforcedStyle: runtime_error

Lint/LambdaWithoutLiteralBlock:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: true
  MaximumRangeSize: .inf

Lint/MissingSuper:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/NonAtomicFileOperation:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Lint/PercentStringArray:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/RedundantCopEnableDirective:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: true
  AllowedMethods:
    - present?
    - blank?
    - presence
    - try
    - try!

Lint/SafeNavigationConsistency:
  Enabled: true
  AllowedMethods:
    - present?
    - blank?
    - presence
    - try
    - try!

Lint/ScriptPermission:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Lint/ShadowedArgument:
  Enabled: true
  IgnoreImplicitReferences: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: false

Lint/ToJSON:
  Enabled: false

Lint/UnexpectedBlockArity:
  Enabled: false

Lint/UnmodifiedReduceAccumulator:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/UselessElseWithoutRescue:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/Void:
  Enabled: true
  CheckForMethodsWithNoSideEffects: false

Metrics/AbcSize:
  Enabled: false
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CollectionLiteralLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 20
  CountAsOne: ["array", "hash", "heredoc", "method_call"]

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/BlockForwarding:
  Enabled: true
  EnforcedStyle: explicit

Naming/BlockParameterName:
  Enabled: true
  MinNameLength: 1
  AllowNamesEndingInNumbers: true
  AllowedNames: []
  ForbiddenNames: []

Naming/FileName:
  Enabled: false

Naming/HeredocDelimiterCase:
  Enabled: true
  EnforcedStyle: uppercase

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/VariableName:
  Enabled: true
  EnforcedStyle: snake_case

Naming/VariableNumber:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/IncludeExamples:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: true

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectDeclaration:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VariableName:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/LeakyLocalVariable:
  Enabled: true

Security/IoMethods:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/ArrayCoercion:
  Enabled: false

Style/ArrayFirstLast:
  Enabled: false

Style/ArrayIntersect:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: true
  EnforcedStyle: bare_percent

Style/BisectedAttrAccessor:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: true
  EnforcedStyle: is_a?

Style/ClassMethodsDefinitions:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionCompact:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/CommandLiteral:
  Enabled: true
  EnforcedStyle: mixed
  AllowInnerBackticks: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConcatArrayLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: true
  EnforcedStyle: assign_to_condition
  SingleLineConditionsOnly: true
  IncludeTernaryExpressions: true

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DataInheritance:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleCopDisableDirective:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  Enabled: true
  AllowComments: true
  EnforcedStyle: both

Style/EmptyHeredoc:
  Enabled: false

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

Style/Encoding:
  Enabled: false

Style/EndlessMethod:
  Enabled: false

Style/EnvHome:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/ExactRegexpMatch:
  Enabled: true
Style/ExpandPathArguments:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FileEmpty:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/For:
  Enabled: true
  EnforcedStyle: each

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalVars:
  Enabled: true
  AllowedVariables: []

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: either

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/InPatternThen:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/InvertibleUnlessCondition:
  Enabled: false

Style/IpAddresses:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: call

Style/MagicCommentFormat:
  Enabled: false

Style/MapIntoArray:
  Enabled: false

Style/MapToHash:
  Enabled: false

Style/MapToSet:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: true
  AllowedMethods: []

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MinMax:
  Enabled: false

Style/MinMaxComparison:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MixinGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineInPatternThen:
  Enabled: false

Style/MultilineMemoization:
  Enabled: true
  EnforcedStyle: keyword

Style/MultilineMethodSignature:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Style/NegatedUnless:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: true
  AllowedMethods:
    - be
    - be_a
    - be_an
    - be_between
    - be_falsey
    - be_kind_of
    - be_instance_of
    - be_truthy
    - be_within
    - eq
    - eql
    - end_with
    - include
    - match
    - raise_error
    - respond_to
    - start_with

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: true
  EnforcedStyle: predicate

Style/NonNilCheck:
  Enabled: true
  IncludeSemanticChanges: false

Style/NumberedParameters:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: true
  EnforcedOctalStyle: zero_with_o

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ObjectThen:
  Enabled: false

Style/OpenStructUse:
  Enabled: true

Style/OperatorMethodCall:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: true
  AllowSafeAssignment: true
  AllowInMultilineConditions: false

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: ()
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/QuotedSymbols:
  Enabled: true
  EnforcedStyle: same_as_string_literals

Style/RaiseArgs:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/RedundantCapitalW:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RedundantEach:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFilterChain:
  Enabled: false

Style/RedundantInitialize:
  Enabled: false

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/RedundantSelfAssignmentBranch:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RequireOrder:
  Enabled: false

Style/ReturnNil:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Style/SafeNavigation:
  Enabled: true
  ConvertCodeThatCanStartToReturnNil: false
  AllowedMethods:
    - present?
    - blank?
    - presence
    - try
    - try!

Style/SelectByRegexp:
  Enabled: false

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: false

Style/Send:
  Enabled: false

Style/SendWithLiteralMethodName:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineDoEndBlock:
  Enabled: false

Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: false

Style/SoleNestedConditional:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/StaticClass:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/StringMethods:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SwapValues:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TopLevelMethodDefinition:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
  AllowPredicates: true
  AllowDSLWriters: false
  IgnoreClassMethods: true
  AllowedMethods:
    - to_ary
    - to_a
    - to_c
    - to_enum
    - to_h
    - to_hash
    - to_i
    - to_int
    - to_io
    - to_open
    - to_path
    - to_proc
    - to_r
    - to_regexp
    - to_str
    - to_s
    - to_sym

Style/UnlessLogicalOperators:
  Enabled: true
  EnforcedStyle: forbid_mixed_logical_operators

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: true
  EnforcedStyle: forbid_for_all_comparison_operators

Style/YodaExpression:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/BitwisePredicate:
  Enabled: false

Style/SafeNavigationChainLength:
  Max: 4 # Defaults to 2, we should review app in the future and change to default
